### ISSUE TITLE
Environment configuration problem

### ISSUE THREAD

**Issue by jhwvh** [ControlNet/emolysis#1]
Thank you for your outstanding work and open source spirit. Do you have more detailed environment configuration information? There are a lot of packages that conflict.

**Comment by ControlNet** [comment]
If you install from source, following the `service/build_env.sh` should work. Which problem do you meet? Also an easier way is to use the docker.

**Comment by jhwvh** [comment]
Thank you for your timely and patient answer. The environmental problem has been solved !
